version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
      - programming-ui
    ports:
      - 7800:7800

  programming-api:
    build: 
      context: programming-api
      dockerfile: Dockerfile.prod
    image: programming-api-prod
    restart: "on-failure"
    expose:
      - 7777
    depends_on:
      - rabbitmq
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  programming-ui:
    build: 
      context: programming-ui
      dockerfile: Dockerfile.prod
    image: programming-ui-prod
    restart: "on-failure"
    expose:
      - 3000
    depends_on:
      - programming-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  grader-api:
    build: grader-api
    image: grader-api
    restart: "no"
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000

  database:
    container_name: database-server-dab-p1-4f39a9d5-9b37-4b13-b7d4-5693677e9d48
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    profiles:
      - migrate

  pgadmin:
    image: dpage/pgadmin4:6.20
    env_file:
      - project.env
    depends_on:
      - database
    profiles:
      - pgadmin

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672

  grader:
    build: 
      context: grader-api
      dockerfile: Dockerfile.prod
    image: grader-api-prod
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
      - flyway
      - database
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests